### ISSUE TITLE
Exclude aws-sdk from serverless-webpack

### ISSUE THREAD

**Issue by dipasqualew** [comicrelief/serverless-starter-app#21]
`aws-sdk` is available by default in lambda functions so there is no need to bundle it.

```
  webpack:
    packager: 'yarn'
    includeModules:
      forceExclude:
        - aws-sdk
```
